#!/usr/bin/env bash

set -euo pipefail

source "$DOTLY_PATH/scripts/core/_main.sh"

##? Add a hello message
##?
##? Usage:
##?    hello
docs::parse "$@"

echo '    |\__/,|   (`\'
echo "  _.|o o  |_   ) )"
echo "-(((---(((--------"
