#!/bin/sh

if ! bspc wm -g &>/dev/null; then
  exit 1
fi

# Change cursor to pointer
xsetroot -cursor_name left_ptr

# bspwm
export PANEL_FIFO=/tmp/panel-fifo
export PANEL_HEIGHT=24
export PANEL_FONT="-*-fixed-medium-*-normal-*-14-*-100-100-*-*-*-*"
export PANEL_WM_NAME=bspwm_panel
export PANEL_FIFO PANEL_HEIGHT PANEL_FONT PANEL_WM_NAME

bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
bspc config merge_overlapping_monitors [ false, true ]
bspc config split_ratio          0.50
bspc config borderless_monocle   false
bspc config gapless_monocle      false

# Source the bspwm theme
if [[ -f $HOME/.config/bspwm/theme ]]; then
    source $HOME/.config/bspwm/theme
fi

# Launch applications on startup
if [[ -d $HOME/.autostart ]]; then
    for file in $(ls $HOME/.autostart); do
        sh $HOME/.autostart/$file
    done
fi

sxhkd &
