
# Uncomment for debuf with `zprof`
# zmodload zsh/zprof

# ZSH opts
WORDCHARS=${WORDCHARS//[\/]}
ZSH_HIGHLIGHT_HIGHLIGHTERS=(main brackets)
setopt interactivecomments
setopt AUTO_MENU
setopt AUTO_CD
setopt AUTO_NAME_DIRS
setopt HIST_IGNORE_DUPS
setopt HIST_IGNORE_ALL_DUPS
setopt share_history
setopt appendhistory     #Append history to the history file (no overwriting)
setopt sharehistory      #Share history across terminals
setopt incappendhistory  #Immediately append to the history file, not just when a term is killed

if [[ ${ZIM_HOME}/init.zsh -ot ${ZDOTDIR:-${HOME}}/.zimrc ]]; then
  # Update static initialization script if it's outdated, before sourcing it
  source ${ZIM_HOME}/zimfw.zsh init -q
fi
source ${ZIM_HOME}/init.zsh

# Profile
if [ -f ~/.profile ]; then
  source ~/.profile;
fi

source ~/.config/zsh/autojump.zsh;
source ~/.config/zsh/bindings.zsh;
source ~/.config/zsh/vi-mode.zsh;
source ~/.config/zsh/history.zsh;
source ~/.config/zsh/fzf.zsh; 

# zprof
