source ~/.zgen/zgen.zsh

if ! zgen saved; then
  zgen oh-my-zsh

  # Base
  zgen oh-my-zsh plugins/archlinux
  zgen oh-my-zsh plugins/colored-man-pages
  zgen oh-my-zsh plugins/history
  zgen oh-my-zsh plugins/lol
  zgen oh-my-zsh plugins/vi-mode
  zgen oh-my-zsh plugins/wd
  zgen oh-my-zsh plugins/web-search

  # Dev
  zgen oh-my-zsh plugins/bower
  zgen oh-my-zsh plugins/capistrano
  zgen oh-my-zsh plugins/colorize
  zgen oh-my-zsh plugins/composer
  zgen oh-my-zsh plugins/docker
  zgen oh-my-zsh plugins/git
  zgen oh-my-zsh plugins/git-extras
  zgen oh-my-zsh plugins/git-flow
  zgen oh-my-zsh plugins/golang
  zgen oh-my-zsh plugins/kubectl
  zgen oh-my-zsh plugins/redis-cli
  zgen oh-my-zsh plugins/sublime
  zgen oh-my-zsh plugins/tmux
  zgen oh-my-zsh plugins/tmuxinator
  zgen oh-my-zsh plugins/yarn

  zgen load willghatch/zsh-snippets
  zgen load zsh-users/zsh-autosuggestions
  zgen load zsh-users/zsh-history-substring-search
  zgen load zsh-users/zsh-syntax-highlighting
  zgen load denysdovhan/spaceship-prompt spaceship

  # zgen load ~/.config/zsh/oh-my-zsh-themes/frandieguez-v1.zsh-theme

  zgen save
fi
SPACESHIP_TIME_COLOR="blue"
SPACESHIP_USER_PREFIX=""
SPACESHIP_USER_SUFFIX=""
SPACESHIP_DIR_PREFIX=":"
SPACESHIP_DIR_COLOR="red"
SPACESHIP_HOST_SHOW=false
SPACESHIP_HOST_SHOW_FULL=true
SPACESHIP_TIME_SHOW=true
SPACESHIP_GIT_SYMBOL=""
# SPACESHIP_GIT_PREFIX="("
# SPACESHIP_GIT_SUFFIX=") "
SPACESHIP_GIT_BRANCH_PREFIX=""
SPACESHIP_GIT_BRANCH_COLOR="green"
SPACESHIP_GIT_STATUS_COLOR="green"
# SPACESHIP_GIT_STATUS_PREFIX=" "
# SPACESHIP_GIT_STATUS_SUFFIX=""
SPACESHIP_PROMPT_DEFAULT_PREFIX="with"
SPACESHIP_PROMPT_BOLD=false
SPACESHIP_PACKAGE_SHOW=false
SPACESHIP_RUBY_SYMBOL="R "
SPACESHIP_DOCKER_SHOW=false
SPACESHIP_USER_SHOW=always
SPACESHIP_KUBECONTEXT_SHOW=false

# Load zsh configuration
for file in ~/.config/zsh/(config|functions)/*; do
    source "$file"
done

# Profile
if [ -f ~/.profile ]; then
  source ~/.profile;
fi
